[profile.default]
src = "contracts"
test = "test"
script = "script"
out = "out"
solc_version = "0.8.34"
evm_version = "prague"
optimizer = true
optimizer_runs = 200
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
