name: Hardhat CI

on:
  push:
    branches: [dev, master, main]
  pull_request:
    branches: [dev, master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Setup NodeJS 24.12.0
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
        with:
          node-version: 20.5.0

      - name: Show NodeJS version
        run: npm --version

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install Project Dependencies
        run: npm install

      - name: Run Hardhat Test
        run: npx hardhat test