name: CI

on:
  workflow_dispatch:
  push:
    branches: [dev, master, main, wrapped-tokens]
  pull_request:
    branches: [dev, master, main, wrapped-tokens]

env:
  MAINNET_NODE: ${{ secrets.MAINNET_NODE }}
  POLYGON_NODE: ${{ secrets.POLYGON_NODE }}
  HOLESKY_NODE: ${{ secrets.HOLESKY_NODE }}
  SEPOLIA_NODE: ${{ secrets.SEPOLIA_NODE }}
  ARBITRUM_NODE: ${{ secrets.ARBITRUM_NODE }}
  ARBITRUMTESTNET_NODE: ${{ secrets.ARBITRUMTESTNET_NODE }}
  BASE_NODE: ${{ secrets.BASE_NODE }}
  BASETESTNET_NODE: ${{ secrets.BASETESTNET_NODE }}
  BSC_NODE: ${{ secrets.BSC_NODE }}

  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  PRIVATE_KEY: ${{ secrets.DUMMY_PK }}

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup NodeJS 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0

      - name: Show NodeJS version
        run: npm --version

      - name: Install Project Dependencies
        run: npm install

      - name: Run Hardhat Tests
        run: npx hardhat coverage
