name: Slither Analysis

on:
  workflow_dispatch:
  push:
    branches: [dev, master, main, wrapped-assets]
  pull_request:
    branches: [dev, master, main, wrapped-assets]

env:
  MAINNET_NODE: ${{ secrets.MAINNET_NODE }}
  POLYGON_NODE: ${{ secrets.POLYGON_NODE }}
  HOLESKY_NODE: ${{ secrets.HOLESKY_NODE }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  PRIVATE_KEY: ${{ secrets.DUMMY_PK }}

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Run Slither
      uses: crytic/slither-action@v0.3.0
      id: slither
      with:
        node-version: 16
        sarif: results.sarif
        fail-on: none

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}
